using UnityEngine;
using UnityEngine.AI;

public class EnemyAnimController : MonoBehaviour
{
    [Header("References")]
    public Animator animator;
    public EnemyAI ai;
    public NavMeshAgent agent;
    public EnemyCombat combat;
    [Header("Animation Settings")]
    public float walkThreshold = 0.1f;
    public float runThreshold = 3f;

    void Awake()
    {
        if (animator == null)
            animator = GetComponentInChildren<Animator>();

        if (agent == null)
            agent = GetComponent<NavMeshAgent>();
    }

    void Update()
    {
         if (ai == null || animator == null) 
            return;

        if (ai.currentState == EnemyState.Dead)
             return; // ðŸ’€ Ã–LÃœYSE TAMAMEN SUS

        HandleMovementAnimation();
        HandleCombatAnimation();
        //HandleDeathAnimation();
    }

    // =========================
    // HAREKET
    // =========================
    void HandleMovementAnimation()
    {
    // Ajan kapalÄ±ysa veya havadaysa Ã§alÄ±ÅŸma
    if (agent == null || !agent.enabled || !agent.isOnNavMesh) return;

    // Karakterin dÃ¼nya hÄ±zÄ±nÄ± yerel (local) hÄ±za Ã§eviriyoruz
    Vector3 localVelocity = transform.InverseTransformDirection(agent.velocity);
    
    // AnimatÃ¶rdeki "Speed" ileri-geri, "Strafe" saÄŸa-sola parametreleridir.
    animator.SetFloat("Speed", localVelocity.z); 
    animator.SetFloat("Strafe", localVelocity.x);
    }

    // =========================
    // ATEÅž
    // =========================
     void HandleCombatAnimation()
     {
     if (combat == null) return;

        // EnemyCombat iÃ§indeki IsShooting bilgisini Animator'daki ÅŸaltere (bool) baÄŸladÄ±k
        animator.SetBool("IsShooting", combat.IsShooting);
     }
    
    // =========================
    // Ã–LÃœM
    // =========================
   // void HandleDeathAnimation()
   // {
   //     bool dead = ai.currentState == EnemyState.Dead;
   //     animator.SetBool("IsDead", dead);
   // }
}
